import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import kipodaiLogo from '../../logos/kipodai.png';

const Arrow = () => <span aria-hidden="true">→</span>;

function DashboardPreview() {
  return <div className="landing-dashboard" aria-label="Example business dashboard">
    <div className="dashboard-topline"><span className="dashboard-dot" /> Performance overview <span>Last 12 weeks</span></div>
    <div className="dashboard-metrics">
      <div><small>Sales velocity</small><strong>+18.4%</strong><em>↑ 4.8% vs prior period</em></div><div><small>In-stock rate</small><strong>97.8%</strong><em>↑ 1.6 pts this week</em></div><div><small>Revenue</small><strong>$842K</strong><em>↑ 12.1% vs last year</em></div>
    </div>
    <div className="dashboard-chart"><div className="chart-heading"><span>Revenue & availability</span><span className="chart-legend"><i /> Revenue <b /> In stock</span></div>
      <svg viewBox="0 0 620 190" role="img" aria-label="Sales and in-stock trend chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#f06a3a" stopOpacity=".27"/><stop offset="1" stopColor="#f06a3a" stopOpacity="0"/></linearGradient></defs><g className="chart-grid"><path d="M0 35H620M0 95H620M0 155H620" /></g><path fill="url(#area)" d="M0 150 L55 137 L110 145 L165 109 L220 120 L275 72 L330 89 L385 45 L440 69 L495 38 L550 55 L620 14 L620 190 L0 190Z" /><path className="revenue-line" d="M0 150 L55 137 L110 145 L165 109 L220 120 L275 72 L330 89 L385 45 L440 69 L495 38 L550 55 L620 14" /><path className="stock-line" d="M0 119 L55 112 L110 115 L165 95 L220 106 L275 83 L330 91 L385 78 L440 80 L495 61 L550 69 L620 48" /></svg>
    </div><div className="dashboard-footer"><span>Top opportunity: Northeast retail</span><strong>View details <Arrow /></strong></div>
  </div>;
}

const lensOptions = [
  { label: 'Will we have enough?', title: 'See supply before it becomes a sales story.', detail: 'Connect planned shipments, on-hand inventory, and retailer availability to spot the next risk early.', metric: '97.8%', metricLabel: 'in-stock health', tone: 'supply' },
  { label: 'Where are we winning?', title: 'Find the momentum worth leaning into.', detail: 'See the markets and customer segments where velocity is building—and where to invest next.', metric: '+18.4%', metricLabel: 'velocity momentum', tone: 'growth' },
  { label: 'What needs attention?', title: 'Turn noise into a focused next move.', detail: 'Surface the exceptions that matter, with enough context for your team to act quickly.', metric: '3', metricLabel: 'DCs below WoS', tone: 'focus' },
];

function BusinessLens() {
  const [active, setActive] = useState(0);
  const item = lensOptions[active];
  return <section className={`business-lens ${item.tone}`} aria-label="Explore KipodAI insights"><div className="lens-top"><div><p className="eyebrow">Start with a real question</p><h2>What do you need to know today?</h2></div><p>Choose a question to see how KipodAI brings the answer into focus.</p></div><div className="lens-layout"><div className="lens-options">{lensOptions.map((option, index) => <button key={option.label} className={index === active ? 'lens-option active' : 'lens-option'} onClick={() => setActive(index)}><span>0{index + 1}</span>{option.label}<b>↗</b></button>)}</div><div className="lens-answer"><span className="answer-spark">✦</span><p className="answer-label">KipodAI perspective</p><h3>{item.title}</h3><p>{item.detail}</p><div className="answer-metric"><strong>{item.metric}</strong><span>{item.metricLabel}</span></div></div></div></section>;
}

export default function Landing() {
  return <main className="landing-page">
    <a className="floating-contact" href="mailto:hello@kipodai.com?subject=KipodAI%20dashboard%20inquiry" aria-label="Contact KipodAI"><span className="floating-contact-message">Want a clearer view of your business?<b>Let’s talk →</b></span><img src={kipodaiLogo} alt="" /></a>
    <nav className="landing-nav"><Link to="/" className="landing-brand" aria-label="KipodAI home"><img src={kipodaiLogo} alt="KipodAI" /><span>kipodai</span></Link><div className="landing-nav-links"><a href="#solutions">Solutions</a><a href="#how-it-works">How it works</a><a href="#contact">Contact</a><Link className="portal-link" to="/client-portal">Client portal <Arrow /></Link></div></nav>
    <section className="landing-hero hero-preview"><div className="hero-copy"><p className="hero-kicker">Built with you, around you</p><h1>Your business is one of one. Your dashboard should be <span>too.</span></h1><p className="hero-lede">KipodAI creates clear, useful dashboards around your goals and the questions your team needs answered—so sales, inventory, operations, and growth opportunities finally make sense together.</p><div className="hero-actions"><a className="landing-button" href="#contact">Build my dashboard <Arrow /></a><a className="text-action" href="#solutions">See what KipodAI connects <Arrow /></a></div></div><div className="hero-visual"><div className="hero-glow" /><DashboardPreview /></div></section>
    <BusinessLens />
    <section className="insight-strip"><div className="insight-strip-copy"><p className="eyebrow">Less digging. More doing.</p><h2>From scattered data to a clear next move.</h2></div><div className="insight-flow" aria-label="Data sources flow into decision-ready dashboards"><div><i className="source-icon bars-icon" /><span>Sales</span></div><b>+</b><div><i className="source-icon boxes-icon" /><span>Inventory</span></div><b>+</b><div><i className="source-icon pulse-icon" /><span>Operations</span></div><strong>→</strong><div className="insight-outcome"><i className="source-icon spark-icon" /><span>Clear decisions</span></div></div></section>
    <section id="solutions" className="solutions-section"><div className="section-intro"><p className="eyebrow">What we build</p><h2>One place to see what matters.</h2><p>Every dashboard is tailored to the decisions your team needs to make—not a generic template full of noise.</p></div><div className="solution-grid"><article><span className="solution-number">01</span><h3>Performance dashboards</h3><p>See sales, velocity, margin, and customer trends in a single, beautifully organized view.</p><div className="mini-bars"><i /><i /><i /><i /></div></article><article><span className="solution-number">02</span><h3>Inventory & supply signals</h3><p>Spot availability issues, service trends, and supply risks before they become missed sales.</p><div className="mini-signal"><b /><b /><b /><b /><b /></div></article><article><span className="solution-number">03</span><h3>Opportunity maps</h3><p>Find the markets, products, and customers where the next meaningful gains are waiting.</p><div className="mini-map"><i /><i /><i /><i /><i /></div></article></div></section>
    <section className="showcase-section"><i className="showcase-orb orb-one" /><i className="showcase-orb orb-two" /><div className="showcase-intro"><p className="eyebrow">A fuller view of the business</p><h2>See your plan through your customers’ reality.</h2><p>You know what you planned to ship and when. KipodAI brings that together with what your customers are actually seeing at retail—so every decision starts with the full story.</p></div><div className="showcase-grid"><figure><img src="/images/supply-demand-dashboard.svg" alt="Example supply and demand dashboard comparing supplier shipments and retailer sell-through" /><figcaption><span>Supply & demand</span><p>See where your plan is headed and how it is translating for customers.</p></figcaption></figure><figure><img src="/images/market-performance-map.png" alt="Example United States market velocity map" /><figcaption><span>Market performance</span><p>See where customer momentum and availability are strongest.</p></figcaption></figure></div></section>
    <section id="how-it-works" className="process-section"><div><p className="eyebrow">Simple by design</p><h2>From scattered data to shared direction.</h2></div><ol><li><span>1</span><div><h3>Connect the dots</h3><p>We learn your business and bring the right data together.</p></div></li><li><span>2</span><div><h3>Make it useful</h3><p>We shape information into clear signals and intuitive views.</p></div></li><li><span>3</span><div><h3>Move with confidence</h3><p>Your team gets the visibility to act on what matters next.</p></div></li></ol></section>
    <section id="contact" className="contact-section"><div><p className="eyebrow">Start a conversation</p><h2>Let’s make your data work harder.</h2><p>Tell us what you need to see more clearly. We’ll help you imagine the dashboard that gets you there.</p></div><a className="landing-button light-button" href="mailto:hello@kipodai.com?subject=KipodAI%20dashboard%20inquiry">Contact us <Arrow /></a></section><footer className="landing-footer"><Link to="/" className="landing-brand"><img src={kipodaiLogo} alt="" /><span>kipodai</span></Link><span>© {new Date().getFullYear()} KipodAI. Clearer decisions, every day.</span></footer>
  </main>;
}
